// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViralExposure;

namespace ViralExposure.Migrations
{
    [DbContext(typeof(CovidContext))]
    partial class CovidContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ViralExposure.TownCovidInfo", b =>
                {
                    b.Property<string>("town_no")
                        .HasColumnType("text");

                    b.Property<string>("caserate")
                        .HasColumnType("text");

                    b.Property<string>("confirmedcases")
                        .HasColumnType("text");

                    b.Property<string>("deaths")
                        .HasColumnType("text");

                    b.Property<DateTime>("lastupdateddate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("peopletested")
                        .HasColumnType("text");

                    b.Property<string>("town")
                        .HasColumnType("text");

                    b.HasKey("town_no");

                    b.ToTable("TownCovidInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
